### PR TITLE
Guzzle 7

### PR DESCRIPTION
**Pull request by MGatner**
Building on the work by @djjavo this moves the Guzzle dependency to version 7. The only issue is that there is currently a "workaround" for the `getRouteAs___()` methods, which appear to return XML instead of JSON: https://github.com/basvandorst/StravaPHP/blob/35d1048bc08b38d1b3786cbe88639fcdc88588c2/src/Strava/API/Service/REST.php#L67-L70

Since Guzzle responses are now typed the test mock won't work anymore, and I don't have a way to see what the actual responses are. Someone with a "live" connection could test using Guzzle 7 and we could update the mocking, or this can be left untested.

As a side note, a lot of the tests are all mocked so it is possible there are some more Guzzle incompatibilities hidden in there. But barring that, nothing else conflicts with Guzzle 6, so an alternate approach would be to allow either version in Composer: `"guzzlehttp/guzzle": "^6.3 || ^7.0.1",`

### CODE REVIEW

**Comment by djjavo** [comment]
I can't remember why we didn't upgrade to Guzzle 7 on master, @vredeling do you remember? Either way, I think it would be good to get this in master. Maybe include backward comparability if required?

**Comment by MGatner** [comment]
I think going with the 6-or-7 approach would be ideal. I put 7 here because that's what was already in place on the `guzzle7` branch but I'm happy to change it.

**Review by vredeling — APPROVED** [review]

**Comment by vredeling** [comment]
Thanks @MGatner and @djjavo !

**Comment by MGatner** [comment]
Just FYI semver does *not* require a major version for dependency changes - it is fine to increase the dependency in a minor release and let package managers handle the result.

**Pull request merged**
