### PR TITLE
Guzzle http client fixes

### PR DESCRIPTION
**Pull request by vredeling**
Strava endpoint needs a trailing slash for Guzzle http client. Otherwise the client will revert to https://www.strava.com/api/ and all api requests will return a 404.

### CODE REVIEW

**Comment by vredeling** [comment]
The solution in #48 is more complete. Closing this in favor of the other patch.

**Comment by vredeling** [comment]
Merged #45 and #48

**Comment by vredeling** [comment]
@fbonzon could you take a look at #44 #45 #47 #48 and #49? I've contacted @basvandorst who is not able to review these issues and pr's currently.

**Comment by fbonzon** [comment]
Hi @vredeling. I'm not able either to review these PRs in the immediate future, unfortunately. I'll get back to active work here asap.

**Comment by vredeling** [comment]
@fbonzon thanks for the reply. FTTB I'll continue working in my own fork.

**Comment by natatkinson** [comment]
Please merge this into production!

**Comment by beararmy** [comment]
Damn it man, merge it already!

image

**Comment by vredeling** [comment]
@natatkinson @beararmy I intend to continue development of the Strava PHP library on my fork. See: https://github.com/vredeling/StravaPHP and https://packagist.org/packages/vredeling/stravaphp

**Pull request closed without merging**
