### PR TITLE
Update oauth2 client to v2.3 & replace PEST with Guzzle.

### PR DESCRIPTION
**Pull request by vredeling**
Should prevent deprecated errors mentioned in #21 and #40

### CODE REVIEW

**Comment by vredeling** [comment]
Checked this on PHP 7. Test config / min requirements are 5.5.

**Comment by vredeling** [comment]
I've raised the php requirements to 7.0+. Now it passes build checks. I believe the oauth client is also compatible with 5.6. So if 7.0 is too high, I could reroll this PR to try 5.6. But honestly I think adopting 7.0 for the next stable release is perfectly acceptable since php 5 security support will stop at the end of 2018 anyway.

**Comment by vredeling** [comment]
Added a php 5.6 commit... works fine too.

**Comment by basvandorst** [comment]
Thanks a lot @vredeling, cheers!

**Pull request merged**
